<div class="row">
	<div class="col-xs-12">
		<h2>Create article</h2>
	</div>
</div>
<form method="post" action="?page=create_article" role="form">
	<div class="row">
		<div class="form-group col-xs-12">
			<label for='create_title'>Title</label>
			<input type='text' name='create_title' placeholder='1 to 31 characters' value='<?php if (isset($create_title)) {echo htmlentities($create_title);} ?>' id='create_title' class='form-control' />
		</div>
	</div>
	<div class="row">
		<div class="form-group col-xs-12">
			<label for='create_content'>Content</label>
			<textarea rows="14" name='create_content' placeholder='32 to 2045 characters' id='create_content' class='form-control'><?php if (isset($create_content)) {echo htmlentities($create_content);} ?></textarea>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 text-right">
			<button type='submit' class='btn btn-success'>Submit</button>
		</div>
	</div>
</form>
