<div class="row">
	<div class="article-preview col-xs-12">
		<div class="col-xs-12">
			<a href="?page=article&id=<?php echo($article -> getId()) ?>"><h3><?php echo htmlentities(($article -> getTitle())) ?></h3></a>
		</div>
		<div class="col-xs-6">
			<p>
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
				 <?php echo htmlentities(($article -> getUser() -> getLogin())) ?>
			</p>
		</div>
		<div class="col-xs-6 text-right">
			<p>
				<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
				 <?php echo($article -> getDate()) ?>
			</p>
		</div>
	</div>
</div>
<hr>