<div class="row">
	<div class="col-xs-12">
		<h2>Edit article</h2>
	</div>
</div>
<form method="post" action="?page=edit_article&amp;id=<?php echo $_GET['id'] ?>" role="form">
	<div class="row">
		<div class="form-group col-xs-12">
			<label for='edit_title'>Title</label>
			<input type='text' name='edit_title' placeholder='1 to 31 characters' value='<?php echo htmlentities($article -> getTitle()) ?>' id='edit_title' class='form-control' />
		</div>
	</div>
	<div class="row">
		<div class="form-group col-xs-12">
			<label for='edit_content'>Content</label>
			<textarea rows="14" name='edit_content' placeholder='32 to 2045 characters' id='edit_content' class='form-control'><?php echo htmlentities($article -> getContent()) ?></textarea>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 text-right">
			<button type='submit' class='btn btn-success'>Submit</button>
		</div>
	</div>
</form>
