<div class="row">
	<div class="article-title col-xs-12">
		<h2>
			<?php echo htmlentities($article -> getTitle()) ?>
			<a href="?page=edit_article&id=<?php echo $article -> getId() ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></a>
		</h2>
	</div>
</div>
<div class="row">
	<div class="article-infos">
		<div class="article-author col-xs-6">
			<p>
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
				<em>By <?php echo htmlentities($article -> getUser() -> getLogin()) ?></em>
			</p>
		</div>
		<div class="article-date col-xs-6 text-right">
			<p>
				<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
				<em><?php echo htmlentities($article -> getDate()) ?></em>
			</p>
		</div>
	</div>
</div>
<hr>
<div class="row">
	<div class="article-content col-xs-12">
		<p><?php echo htmlentities($article -> getContent()) ?></p>
	</div>
</div>