<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div id="navbar" class="navbar-collapse collapse">                
			<ul class="nav navbar-nav navbar-right">
			<?php if(isset($_SESSION['id'])) { ?>
				<li><a href="?page=articles">Articles</a></li>
				<li><a href="?page=create_article">Create</a></li>
				<li><a href="?page=logout">Logout</a></li>
			<?php } else { ?>
			<li><a href="?page=articles">Articles</a></li>
				<li><a href="?page=login">Login </a></li>
				<li><a href="?page=register">Register</a></li>
			<?php } ?>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container -->
</nav>