<!DOCTYPE html>
<html lang="fr">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Blog Post - Start Bootstrap Template</title>

	<!-- Bootstrap Core CSS -->
	<link href="public/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<!-- Custom CSS -->
	<link href="public/css/style.css" rel="stylesheet">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Blog Post - Start Bootstrap Template</title>

	<!-- jQuery -->
	<script src="public/js/jquery.min.js"></script>

	<!-- Bootstrap Core CSS -->
	<link href="public/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="public/css/style.css" rel="stylesheet">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>	

	<?php require('controllers/menu.php') ?>
	
	<?php require('./controllers/header.php'); ?>					
				
	<div id="page-content-wrapper">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<?php require('controllers/errors.php') ?>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<?php require('controllers/content.php'); ?>
				</div>
			</div>
		</div>
	</div>

	<?php require('./controllers/footer.php'); ?>
	
	<!-- Bootstrap Core JavaScript -->
	<script src="public/js/bootstrap.min.js"></script>
</body>
</html>